# Generated by Django 2.2.7 on 2019-11-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.FileField(upload_to='files/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('paintout', models.ImageField(upload_to='results/')),
                ('area_ratio', models.IntegerField(default=0, null=True)),
                ('copymove', models.ImageField(upload_to='results/')),
                ('mask_ratio', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
